targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      slang_build_runner:
        options:
          base_locale: ru
          translate_var: translations
          fallback_strategy: base_locale
          input_directory: assets/translations/
          output_directory: lib/generated/
